MESSAGE_SEND = "message:send"
MESSAGE_EDIT = "message:edit"
MESSAGE_DELETE = "message:delete"
MESSAGE_READ = "message:read"
TYPING_START = "typing:start"
TYPING_STOP = "typing:stop"

MESSAGE_RECEIVED = "message:received"
MESSAGE_UPDATED = "message:updated"
MESSAGE_DELETED = "message:deleted"
MESSAGE_READ_BY = "message:read_by"
TYPING_INDICATOR = "typing:indicator"
USER_PRESENCE = "user:presence"
ERROR = "error"
